name = "ywam-sendai-guide"
compatibility_date = "2026-05-04"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"

[observability]
enabled = false

# Bindings for the AI Chatbot logic
[[vectorize]]
binding = "VECTORIZE"
index_name = "ywam-guide-index"

[ai]
binding = "AI"